development: &default
  adapter: postgresql
  encoding: unicode
  database: tjohn_dev
  username: postgres
  password:
  pool: 5
  min_messages: WARNING

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] || 'tjohn_production' %>
  username: <%= ENV['RDS_USERNAME'] || 'postgres' %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] || 'localhost' %>
  port: <%= ENV['RDS_PORT'] %>
