development:
  adapter: postgresql
  encoding: unicode
  database: tjohn_dev
  username: postgres
  password:
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  database: tjohn_production
  pool: 5
  username: postgres
  password:
  min_messages: WARNING
