development:
  adapter: postgresql
  encoding: unicode
  database: tjohn_dev
  username: postgres
  password:
  pool: 5
  min_messages: WARNING

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  min_messages: WARNING
  database: <%= ENV['RDS_DB_NAME'] || tjohn_production %>
  username: <%= ENV['RDS_USERNAME'] || postgres %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
